version: "3"
services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle13
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql
  web:
    build: ./
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
volumes:
  db:



